name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - 'v*.*.*'

  #schedule:
    # * is a special character in YAML so string is quoted
    #  every Monday at 4:15 - '15 4 * * 1'
  #  - cron:  '15 4 * * 1'
    
  workflow_dispatch:   

  # Run tests for any PRs.
  pull_request:


jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            qwazer/atlassian-sdk-confluence
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
