name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  schedule:
    # * is a special character in YAML so string is quoted
    #  every Monday at 4:15 - '15 4 * * 1'
    - cron:  '15 4 * * 1'

  # Run tests for any PRs.
  pull_request:


jobs:

  build-push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'schedule'

    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: qwazer/atlassian-sdk-confluence
          tag_with_ref: true
